- hosts: metsatpi
  gather_facts: false
  vars:
    srcdir: /mnt/c/Users/{{ lookup('env','USER' )}}/OneDrive/dev/weather/apis_services/bresser_rtl433
    targdir: ~/source/bresser
  environment: 
    LD_LIBRARY_PATH: /usr/local/lib
  tasks:

  - name: Copy files
    copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
    with_items:
    - {src: '{{srcdir}}/bresser_rtl433.service', dest: '{{targdir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/rtl_433.conf', dest: '{{targdir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/installservice.sh', dest: '{{targdir}}/', mode: '744', backup: yes }

  - name: update conf dir
    ansible.builtin.replace:
      path: '{{targdir}}/bresser_rtl433.service'
      regexp: "WORKINGDIR"
      replace: "{{ ansible_env.HOME }}/source/bresser"

