- hosts: weatherpi3 #ukmonhelper
  vars_files: 
    - /mnt/c/Users/{{ lookup('env','USER' )}}/apikeys/mqvariables.enc
  vars:
    srcdir: "/mnt/c/Users/{{ lookup('env','USER' )}}/OneDrive/dev/weather/apis_services/getbresserwu"
    wudir: "{{ ansible_env.HOME }}/source/getbresswu"
  environment: 
    LD_LIBRARY_PATH: /usr/local/lib
  tasks:
  - name: Copy files
    copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
    with_items:
    - {src: '{{srcdir}}/getwu.py', dest: '{{wudir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/wuconfig.py', dest: '{{wudir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/mqConfig.py', dest: '{{wudir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/getBresserData.sh', dest: '{{wudir}}/', mode: '754', backup: yes }
    - {src: '{{srcdir}}/installGetWu.sh', dest: '{{wudir}}/', mode: '754', backup: yes }
    - {src: '{{srcdir}}/getbresswu.service', dest: '{{wudir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/requirements.txt', dest: '{{wudir}}/', mode: '644', backup: yes }

  - name: update broker
    ansible.builtin.replace:
      path: '{{wudir}}/mqConfig.py'
      regexp: "someserver.net"
      replace: "metsatpi"

  - name: update mquser
    ansible.builtin.replace:
      path: '{{wudir}}/mqConfig.py'
      regexp: "mquser"
      replace: "sensors"

  - name: update mqpass
    ansible.builtin.replace:
      path: '{{wudir}}/mqConfig.py'
      regexp: "mqpass"
      replace: "{{ mqsenspassword }}"

  - name: update mqport 
    ansible.builtin.replace:
      path: '{{wudir}}/mqConfig.py'
      regexp: "1883"
      replace: "1883"

  - name: update SRCDIR
    ansible.builtin.replace:
      path: '{{wudir}}/getbresswu.service'
      regexp: "SRCDIR"
      replace: "{{ wudir }}"

  - name: update HOMEDIR
    ansible.builtin.replace:
      path: '{{wudir}}/getBresserData.sh'
      regexp: "HOMEDIR"
      replace: "{{ ansible_env.HOME }}"

