- hosts: wordpresssite
  vars:
    srcdir: /mnt/e/dev/weather/weatherstation/mmwws
    targdir: ~/src/mmwws
  environment: 
    LD_LIBRARY_PATH: /usr/local/lib
  tasks:

  - name: Copy files
    copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
    with_items:
    - {src: '{{srcdir}}/createWsFiles.py', dest: '{{targdir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/convertLegacyData.py', dest: '{{targdir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/wsCreator.sh', dest: '{{targdir}}/', mode: '744', backup: yes }
    - {src: '{{srcdir}}/requirements.txt', dest: '{{targdir}}/', mode: '644', backup: yes }

#  - name: update broker bmp280
#    ansible.builtin.replace:
#      path: '{{targdir}}/readBmp280/mqConfig.py'
#      regexp: "someserver.net"
#      replace: "wxsatpi"
