- hosts: wordpresssite
  vars:
    srcdir: /mnt/e/dev/weather/weatherstation/mmwws
    targdir: ~/src/mmwws
  environment: 
    LD_LIBRARY_PATH: /usr/local/lib
  tasks:

  - name: Copy files
    copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
    with_items:
    - {src: '{{srcdir}}/sendToServices.py', dest: '{{targdir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/conversions.py', dest: '{{targdir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/serviceUploader.sh', dest: '{{targdir}}/', mode: '744', backup: yes }
    - {src: '{{srcdir}}/windRose.py', dest: '{{targdir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/createWsFiles.py', dest: '{{targdir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/createMthlyFiles.py', dest: '{{targdir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/createHourlyFiles.py', dest: '{{targdir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/tableData.py', dest: '{{targdir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/tableHeaders.py', dest: '{{targdir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/windData.py', dest: '{{targdir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/tempPressData.py', dest: '{{targdir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/rainData.py', dest: '{{targdir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/convertLegacyData.py', dest: '{{targdir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/convertOHdata.py', dest: '{{targdir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/wsCreator.sh', dest: '{{targdir}}/', mode: '744', backup: yes }
    - {src: '{{srcdir}}/hourlyCreator.sh', dest: '{{targdir}}/', mode: '744', backup: yes }
    - {src: '{{srcdir}}/mthlyCreator.sh', dest: '{{targdir}}/', mode: '744', backup: yes }
    - {src: '{{srcdir}}/mergeData.sh', dest: '{{targdir}}/', mode: '744', backup: yes }
    - {src: '{{srcdir}}/requirements.txt', dest: '{{targdir}}/', mode: '644', backup: yes }
