- hosts: weatherpi3
  vars:
    srcdir: /mnt/e/dev/weather/weatherstation/apis_services/weatherapi
    apidir: ~/weather/weatherapi
  tasks:
  - name: Copy files
    copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
    tags: [aws, local]
    with_items:
    - {src: '{{srcdir}}/weatherapi.py', dest: '{{apidir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/getLastData.py', dest: '{{apidir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/requirements.txt', dest: '{{apidir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/startup.sh', dest: '{{apidir}}/', mode: '754', backup: yes }
    - {src: '{{srcdir}}/stop.sh', dest: '{{apidir}}/', mode: '754', backup: yes }
    - {src: '{{srcdir}}/weatherapi.service', dest: '{{apidir}}/', mode: '644', backup: yes }
