- hosts: weatherpi3
  gather_facts: false
  vars_files: 
    - /mnt/e/dev/apikeys/mqvariables.enc
  vars:
    srcdir: /mnt/e/dev/weather/weatherstation/apis_services/
    targdir: ~/weather
  environment: 
    LD_LIBRARY_PATH: /usr/local/lib
  tasks:

  - name: Copy files
    copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
    with_items:
    - {src: '{{srcdir}}/rtl433ToMQ/installservice.sh', dest: '{{targdir}}/rtl433/', mode: '744', backup: yes }
    - {src: '{{srcdir}}/rtl433ToMQ/rtlToMQ.sh', dest: '{{targdir}}/rtl433/', mode: '744', backup: yes }
    - {src: '{{srcdir}}/rtl433ToMQ/runRtl433.sh', dest: '{{targdir}}/rtl433/', mode: '744', backup: yes }
    - {src: '{{srcdir}}/rtl433ToMQ/stopRtl433.sh', dest: '{{targdir}}/rtl433/', mode: '744', backup: yes }
    - {src: '{{srcdir}}/rtl433ToMQ/mqConfig.py', dest: '{{targdir}}/rtl433/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/rtl433ToMQ/rtl43ToMQ.py', dest: '{{targdir}}/rtl433/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/rtl433ToMQ/requirements.txt', dest: '{{targdir}}/rtl433/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/rtl433ToMQ/rtl_433.service', dest: '{{targdir}}/rtl433/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/rtl433ToMQ/rtl2mq.service', dest: '{{targdir}}/rtl433/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/rtl433ToMQ/rtl-sdr.rules', dest: '{{targdir}}/rtl433/', mode: '644', backup: yes }

  - name: update broker rtl433
    ansible.builtin.replace:
      path: '{{targdir}}/rtl433/mqConfig.py'
      regexp: "someserver.net"
      replace: "wxsatpi"
  - name: update mquser bmp280
    ansible.builtin.replace:
      path: '{{targdir}}/rtl433/mqConfig.py'
      regexp: "someuser"
      replace: "sensors"
  - name: update mqpasswd bmp280
    ansible.builtin.replace:
      path: '{{targdir}}/rtl433/mqConfig.py'
      regexp: "changeme"
      replace: "{{ mqsenspassword }}"
