- hosts: weatherpi3
  gather_facts: false
  vars:
    srcdir: /mnt/e/dev/weather/weatherstation/apis_services/wh1080_433
    targdir: ~/source/wh1080_rtl433
  environment: 
    LD_LIBRARY_PATH: /usr/local/lib
  tasks:

  - name: Copy files
    copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
    with_items:
    - {src: '{{srcdir}}/runwh1080_433.sh', dest: '{{targdir}}/', mode: '744', backup: yes }
    - {src: '{{srcdir}}/stopwh1080_433.sh', dest: '{{targdir}}/', mode: '744', backup: yes }
    - {src: '{{srcdir}}/wh1080_rtl433.service', dest: '{{targdir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/rtl-sdr.rules', dest: '{{targdir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/installservice.sh', dest: '{{targdir}}/', mode: '744', backup: yes }
