- hosts: weatherpi3
  vars:
    srcdir: /mnt/e/dev/weather/weatherstation/dummyUsbDevice
    targdir: ~/weather
    pywwsdir: ~/venvs/pywws/lib/python3.9/site-packages/pywws

  environment: 
    LD_LIBRARY_PATH: /usr/local/lib
  tasks:
  - name: Copy files
    copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
    with_items:
    - {src: '{{srcdir}}/dummyUsbReader.py', dest: '{{pywwsdir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/weatherstation.py', dest: '{{pywwsdir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/test_dummyusb.py', dest: '{{targdir}}/', mode: '644', backup: yes }
    
