- hosts: wordpresssite
  vars:
    srcdir: /mnt/e/dev/weather/weatherstation/apis_services/getDataAws
    apidir: ~/src/weatherprocessor
  tasks:

  - name: Copy files
    copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
    tags: [aws, local]
    with_items:
    - {src: '{{srcdir}}/getData.py', dest: '{{apidir}}/', mode: '644', backup: yes }
    #- {src: '{{srcdir}}/apiConfig.py', dest: '{{apidir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/startGetData.sh', dest: '{{apidir}}/', mode: '754', backup: yes }
    - {src: '{{srcdir}}/stopGetData.sh', dest: '{{apidir}}/', mode: '754', backup: yes }
    - {src: '{{srcdir}}/getweatherdata.service', dest: '{{apidir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/requirements.txt', dest: '{{apidir}}/', mode: '754', backup: yes }
