- hosts: weatherpi3
  vars_files: 
    - /mnt/e/dev/apikeys/mqvariables.enc
  vars:
    srcdir: /mnt/e/dev/weather/weatherstation/apis_services/bressrain
    dsdir: "{{ ansible_env.HOME }}/source/bressrain"
  environment: 
    LD_LIBRARY_PATH: /usr/local/lib
  tasks:
  - name: Copy files
    copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
    with_items:
    - {src: '{{srcdir}}/getBressRain.sh', dest: '{{dsdir}}/', mode: '754', backup: yes }
    - {src: '{{srcdir}}/bressrain.timer', dest: '{{dsdir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/bressrain.service', dest: '{{dsdir}}/', mode: '644', backup: yes }
  - name: update mquser 
    ansible.builtin.replace:
      path: '{{dsdir}}/getBressRain.sh'
      regexp: "mquser"
      replace: "sensors"
  - name: update mqpasswd 
    ansible.builtin.replace:
      path: '{{dsdir}}/getBressRain.sh'
      regexp: "changeme"
      replace: "{{ mqsenspassword }}"

  - name: update SRCDIR
    ansible.builtin.replace:
      path: '{{dsdir}}/bressrain.service'
      regexp: "SRCDIR"
      replace: "{{ dsdir }}"
