- hosts: weatherpi3
  vars_files: 
    - /mnt/e/dev/weather/weatherstation/keys.enc
  vars:
    srcdir: /mnt/e/dev/weather/weatherstation/apis_services/bressrain
    dsdir: ~/source/bressrain
  environment: 
    LD_LIBRARY_PATH: /usr/local/lib
  tasks:
  - name: Copy files
    copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
    with_items:
    - {src: '{{srcdir}}/getBressRain.sh', dest: '{{dsdir}}/', mode: '754', backup: yes }
  - name: update mquser 
    ansible.builtin.replace:
      path: '{{dsdir}}/getBressRain.sh'
      regexp: "mquser"
      replace: "sensors"
  - name: update mqpasswd 
    ansible.builtin.replace:
      path: '{{dsdir}}/getBressRain.sh'
      regexp: "changeme"
      replace: "{{ mqsenspassword }}"
