- hosts: weatherpi3
  gather_facts: false
  vars_files: 
    - /mnt/c/Users/{{ lookup('env','USER' )}}/apikeys/mqvariables.enc
  vars:
    srcdir: "/mnt/c/Users/{{ lookup('env','USER' )}}/OneDrive/dev/weather/apis_services/maplin2mq"
    targdir: ~/source/maplin2mq
  environment: 
    LD_LIBRARY_PATH: /usr/local/lib
  tasks:

  - name: Copy files
    copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
    with_items:
    - {src: '{{srcdir}}/installservice.sh', dest: '{{targdir}}/', mode: '744', backup: yes }
    - {src: '{{srcdir}}/wh1080_mq.sh', dest: '{{targdir}}/', mode: '744', backup: yes }
    - {src: '{{srcdir}}/mqConfig.py', dest: '{{targdir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/wh1080_mq.py', dest: '{{targdir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/weatherCalcs.py', dest: '{{targdir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/requirements.txt', dest: '{{targdir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/maplin2mq.service', dest: '{{targdir}}/', mode: '644', backup: yes }

  - name: update broker 
    ansible.builtin.replace:
      path: '{{targdir}}/mqConfig.py'
      regexp: "someserver.net"
      replace: "wxsatpi"
  - name: update mquser 
    ansible.builtin.replace:
      path: '{{targdir}}/mqConfig.py'
      regexp: "someuser"
      replace: "sensors"
  - name: update mqpasswd 
    ansible.builtin.replace:
      path: '{{targdir}}/mqConfig.py'
      regexp: "changeme"
      replace: "{{ mqsenspassword }}"
