- hosts: weatherpi3 #ukmonhelper
  vars:
    srcdir: /mnt/e/dev/weather/weatherstation/apis_services/getbresser
    wudir: ~/weather/getwu
  environment: 
    LD_LIBRARY_PATH: /usr/local/lib
  tasks:
  - name: Copy files
    copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
    with_items:
    - {src: '{{srcdir}}/getwu.py', dest: '{{wudir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/wuconfig.py', dest: '{{wudir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/mqConfig.py', dest: '{{wudir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/getBresserData.sh', dest: '{{wudir}}/', mode: '754', backup: yes }
    - {src: '{{srcdir}}/installGetWu.sh', dest: '{{wudir}}/', mode: '754', backup: yes }
    - {src: '{{srcdir}}/getwu.service', dest: '{{wudir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/requirements.txt', dest: '{{wudir}}/', mode: '644', backup: yes }

  - name: update broker
    ansible.builtin.replace:
      path: '{{wudir}}/mqConfig.py'
      regexp: "someserver.net"
      replace: "wxsatpi"

  - name: update mqport 
    ansible.builtin.replace:
      path: '{{wudir}}/mqConfig.py'
      regexp: "1883"
      replace: "1883"
