name: testing 
on:
    push:
        branches: [master]
jobs:
    k8stest:
      name: k8stest
      runs-on: weather-runner
      container:
        image: docker.io/markmac99/wstesting:latest
      steps:
        - uses: actions/checkout@v4
        - name: collect test data
          run: |
            curl -k -H "x-api-key: ${{ secrets.DATAKEY }}" https://192.168.1.195:8081/testdata -o /tmp/testdata.zip
            if [ ! -f $HOME/.ssh/config ] ; then 
              here=$(pwd)
              mkdir $HOME/.ssh
              cd  $HOME/.ssh
              unzip /tmp/testdata.zip
              cd ${here}
              chmod 0700 $HOME/.ssh && chmod 0600 $HOME/.ssh/*
            fi
        - name: install requirements
          run: |
            pip install pytest pytest-cov
        - name: test diskspacechecks
          run: |
            cd ./apis_services/diskspacechecks
            cp /tmp/testConfig.py .
            pytest . --cov=. --cov-report=term-missing
  