name: testing 
on:
    push:
        branches: master
jobs:
    k8stest:
      name: k8stest
      runs-on: thelinux
      # container:
      #   image: docker.io/markmac99/wstesting:latest
      steps:
        - uses: actions/checkout@v4
        - name: runme
          run: |
            sudo apt update -y && sudo apt install curl unzip -y
            curl -k -H "x-api-key: ${{ secrets.DATAKEY }}" https://192.168.1.195:8081/testdata -o /tmp/testdata.zip
            if [ ! -f $HOME/.ssh/config ] ; then 
              mkdir $HOME/.ssh
              pushd $HOME/.ssh
              unzip /tmp/testdata.zip
              popd
            chmod 0700 $HOME/.ssh && chmod 0600 $HOME/.ssh/*
            fi 
            cd ./apis_services/diskspacechecks
            pytest -v .
          
    #tests:
    #  name: tests
    #  runs-on: thelinuxnative # this is a github runner on my Linux box
    #  container:
    #    image: docker.io/markmac99/wstesting:latest # this is the docker image built in this repo
    #    env:
    #      MYENV: foo
    #    ports:
    #      - 22
    #      - 443
    #  strategy:
    #    matrix:
    #      python-version: ["3.7"] #, "3.8", "3.9", "3.10", "3.11"]
    #  steps:
    #    - uses: actions/checkout@v4
    #    - name: run tests
    #      run: |
    #        cd ./apis_services/diskspacechecks
    #        echo HOME is $HOME
     #       if [ ! -f $HOME/.ssh/config ] ; then 
     #         mkdir $HOME/.ssh
     #         cp /sshkeys/* $HOME/.ssh
     #         chmod 0700 $HOME/.ssh && chmod 0600 $HOME/.ssh/*
     #       fi 
     #       pytest -v .
