name: testing 
on:
    push:
        branches: master
jobs:
    tests:
      name: tests
      runs-on: thelinux
      container:
        image: docker.io/markmac99/rmstestcont:latest
        env:
          MYENV: foo
        ports:
          - 22
          - 443
      strategy:
        matrix:
          python-version: ["3.7"] #, "3.8", "3.9", "3.10", "3.11"]
      steps:
        - uses: actions/checkout@v3
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}
        - name: run tests
          run: |
            chmod +x ./tests/*.sh
            ./tests/tests.sh
